version : 0.1
phases:
  install:
    commands:
      - echo installing depandancies...
      - curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
      - yum -y install nodejs
      - node -v
  pre_build:
    commands:
      - echo Installing dependancies...
      - npm install
  build:
    commands:
      - echo Building static assets...........
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
